Description: >
  It will also create an s3 bucket to upload sample website files to.
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:
  #Create S3 bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket to upload sample website files
    Properties:
      BucketName: udagramapp-bucket
